replicaCount: 1

image: sergeydz\go-sample-rest:latest
imagepullPolicy: Always

container:
  port: 8080

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 300Mi
