apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-sample.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
