---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
spec:
  releaseName: nginx
  chart:
    git: ssh://git@github.com/SergeyDz/flux-get-started
    ref: master
    path: charts/nginx
