---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: nginx
  chart:
    git: ssh://git@github.com/SergeyDz/flux-get-started
    ref: master
    path: charts/nginx
  values:
    image: 
      repository: nginx
      tag: alpine
      pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: ClusterIP
      port: 8888
