---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:1.21.*
spec:
  releaseName: nginx
  chart:
    git: ssh://git@github.com/SergeyDz/flux-get-started
    ref: master
    path: charts/nginx
